apiVersion: v1
data:
  username: {{ .Values.controller.wallarm.username | b64enc | quote }}
  password: {{ .Values.controller.wallarm.password | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "nginx-ingress.wallarmSecret" . }}
type: Opaque
